name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Baixar Resultado da Caixa
        run: curl -k -s -L --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://servicebus2.caixa.gov.br/portaldeloterias/api/megasena/" > resultado.json

      # --- INÍCIO DO PASSO DE INJEÇÃO PARA O AMBIENTE DEV ---
      - name: Injetar Visual de DEV (Apenas na branch dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          # 1. Troca o azul pelo vermelho no CSS
          sed -i 's/#005ca9/#cc0000/g' style.css
          
          # 2. Insere a barra de aviso no rodapé do HTML
          sed -i 's/<\/body>/<div style="position: fixed; bottom: 0; width: 100%; background-color: #cc0000; color: white; text-align: center; padding: 10px; font-weight: bold; box-shadow: 0 -2px 10px rgba(0,0,0,0.5);">🚨 AMBIENTE DE DESENVOLVIMENTO (DEV) 🚨<\/div><\/body>/i' index.html
      # --- FIM DO PASSO DE INJEÇÃO ---

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_02131B110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: "" 
          output_location: "." 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_02131B110 }}
          action: "close"